# Generated by Django 5.1.3 on 2025-04-30 21:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReidLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('new_id', 'New ID'), ('rename', 'Rename ID'), ('gallery_loaded', 'Gallery Loaded'), ('gallery_saved', 'Gallery Saved')], max_length=20)),
                ('message', models.TextField()),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera')),
            ],
        ),
    ]
